ALTER TABLE Client DROP FOREIGN KEY client_ibfk_1 ;
ALTER TABLE Groups DROP FOREIGN KEY groups_ibfk_1 ;
ALTER TABLE Groups DROP FOREIGN KEY groups_ibfk_2 ;
ALTER TABLE Project DROP FOREIGN KEY project_ibfk_1 ;
ALTER TABLE Project DROP FOREIGN KEY project_ibfk_2 ;
ALTER TABLE Project DROP FOREIGN KEY project_ibfk_3 ;
ALTER TABLE Task DROP FOREIGN KEY task_ibfk_3 ;
ALTER TABLE Task DROP FOREIGN KEY task_ibfk_4 ;